"""Demo bin locations.

IMPORTANT, and worth repeating to a judge who asks:

    This is DEMO DATA, not an official bin registry.

The venues are real, publicly known Singapore locations, and the kinds of bins listed
are the kinds those venues typically host - NEA requires a blue commingled recycling bin
at HDB blocks, and e-waste collection points are commonly sited at malls, community
clubs and campuses. But the coordinates are approximate landmark positions and the
individual bins are invented. Nothing here is scraped from or endorsed by NEA or ALBA.

The Ecovolt brief explicitly permits this: "No real sensors, hardware, or live data.
You may invent or mock any inputs."

The cluster around NUS Kent Ridge exists so the demo works at the judging table.
"""

# type: the bin's primary stream. accepted: everything it will take.
BIN_SEEDS: list[dict] = [
    # --- NUS Kent Ridge campus: the bins the live demo will use -----------------
    {
        "qr_code_id": "sg-nus-lib-01",
        "name": "NUS Central Library - recycling point",
        "type": "recycling",
        "accepted_waste_types": ["recycling"],
        "latitude": 1.2966,
        "longitude": 103.7729,
        "address": "12 Kent Ridge Crescent, Singapore 119275",
        "opening_hours": "24 hours",
        "notes": "Paper, plastic, metal and glass. Rinse containers before binning.",
    },
    {
        "qr_code_id": "sg-nus-utown-01",
        "name": "NUS University Town - Stephen Riady Centre",
        "type": "recycling",
        "accepted_waste_types": ["recycling"],
        "latitude": 1.3045,
        "longitude": 103.7727,
        "address": "2 College Avenue West, Singapore 138607",
        "opening_hours": "24 hours",
        "notes": "Next to the bus stop on the ground floor.",
    },
    {
        "qr_code_id": "sg-nus-eng-ew-01",
        "name": "NUS Faculty of Engineering - e-waste point",
        "type": "e_waste",
        "accepted_waste_types": ["e_waste"],
        "latitude": 1.2985,
        "longitude": 103.7710,
        "address": "9 Engineering Drive 1, Singapore 117575",
        "opening_hours": "Mon-Fri 08:00-20:00",
        "notes": "Laptops, phones, cables, batteries, small appliances. No CRT monitors.",
    },
    {
        "qr_code_id": "sg-nus-yih-ew-01",
        "name": "NUS Yusof Ishak House - e-waste bin",
        "type": "e_waste",
        "accepted_waste_types": ["e_waste"],
        "latitude": 1.2988,
        "longitude": 103.7745,
        "address": "31 Lower Kent Ridge Road, Singapore 119078",
        "opening_hours": "Mon-Sat 08:00-22:00",
        "notes": "Batteries, bulbs, phones and small IT equipment.",
    },
    {
        "qr_code_id": "sg-nus-krmrt-01",
        "name": "Kent Ridge MRT - concourse recycling bin",
        "type": "recycling",
        "accepted_waste_types": ["recycling"],
        "latitude": 1.2933,
        "longitude": 103.7845,
        "address": "301 South Buona Vista Road, Singapore 118177",
        "opening_hours": "05:30-00:30",
        "notes": "Near the faregates. Drinks containers only, please empty them first.",
    },
    {
        "qr_code_id": "sg-nus-pgp-01",
        "name": "Prince George's Park Residences - block recycling bin",
        "type": "recycling",
        "accepted_waste_types": ["recycling", "e_waste"],
        "latitude": 1.2913,
        "longitude": 103.7807,
        "address": "27 Prince George's Park, Singapore 118425",
        "opening_hours": "24 hours",
        "notes": "Blue commingled bin plus a small e-waste box at the residence office.",
    },
    # --- Around Clementi / one-north -------------------------------------------
    {
        "qr_code_id": "sg-clementi-mall-ew",
        "name": "The Clementi Mall - e-waste collection point",
        "type": "e_waste",
        "accepted_waste_types": ["e_waste"],
        "latitude": 1.3150,
        "longitude": 103.7645,
        "address": "3155 Commonwealth Avenue West, Singapore 129588",
        "opening_hours": "10:00-22:00",
        "notes": "Level 1 near the atrium. ICT equipment, batteries and bulbs.",
    },
    {
        "qr_code_id": "sg-clementi-mrt-01",
        "name": "Clementi MRT - recycling bin",
        "type": "recycling",
        "accepted_waste_types": ["recycling"],
        "latitude": 1.3151,
        "longitude": 103.7654,
        "address": "3151 Commonwealth Avenue West, Singapore 129581",
        "opening_hours": "05:30-00:30",
    },
    {
        "qr_code_id": "sg-buonavista-01",
        "name": "Buona Vista MRT - recycling bin",
        "type": "recycling",
        "accepted_waste_types": ["recycling"],
        "latitude": 1.3072,
        "longitude": 103.7900,
        "address": "231 North Buona Vista Road, Singapore 139659",
        "opening_hours": "05:30-00:30",
    },
    {
        "qr_code_id": "sg-onenorth-ew-01",
        "name": "Fusionopolis - e-waste bin",
        "type": "e_waste",
        "accepted_waste_types": ["e_waste"],
        "latitude": 1.2996,
        "longitude": 103.7876,
        "address": "1 Fusionopolis Way, Singapore 138632",
        "opening_hours": "Mon-Fri 08:00-19:00",
        "notes": "Lobby level. Popular for laptops and monitors.",
    },
    {
        "qr_code_id": "sg-dover-01",
        "name": "Dover MRT - recycling bin",
        "type": "recycling",
        "accepted_waste_types": ["recycling"],
        "latitude": 1.3113,
        "longitude": 103.7786,
        "address": "20 Dover Road, Singapore 138678",
        "opening_hours": "05:30-00:30",
    },
    {
        "qr_code_id": "sg-westcoast-ew-01",
        "name": "West Coast Plaza - e-waste point",
        "type": "e_waste",
        "accepted_waste_types": ["e_waste"],
        "latitude": 1.3040,
        "longitude": 103.7645,
        "address": "154 West Coast Road, Singapore 127371",
        "opening_hours": "10:00-22:00",
    },
    {
        "qr_code_id": "sg-holland-01",
        "name": "Holland Village - blue recycling bin",
        "type": "recycling",
        "accepted_waste_types": ["recycling"],
        "latitude": 1.3111,
        "longitude": 103.7960,
        "address": "Lorong Mambong, Singapore 277700",
        "opening_hours": "24 hours",
    },
    # --- Wider Singapore: gives the radius filter something to exclude ----------
    {
        "qr_code_id": "sg-vivocity-ew-01",
        "name": "VivoCity - e-waste collection point",
        "type": "e_waste",
        "accepted_waste_types": ["e_waste"],
        "latitude": 1.2644,
        "longitude": 103.8222,
        "address": "1 HarbourFront Walk, Singapore 098585",
        "opening_hours": "10:00-22:00",
        "notes": "Basement 2, near the taxi stand.",
    },
    {
        "qr_code_id": "sg-imm-ew-01",
        "name": "IMM Building - e-waste point",
        "type": "e_waste",
        "accepted_waste_types": ["e_waste"],
        "latitude": 1.3350,
        "longitude": 103.7465,
        "address": "2 Jurong East Street 21, Singapore 609601",
        "opening_hours": "10:00-22:00",
    },
    {
        "qr_code_id": "sg-toapayoh-01",
        "name": "Toa Payoh HDB Hub - blue recycling bin",
        "type": "recycling",
        "accepted_waste_types": ["recycling"],
        "latitude": 1.3324,
        "longitude": 103.8470,
        "address": "480 Lorong 6 Toa Payoh, Singapore 310480",
        "opening_hours": "24 hours",
    },
    {
        "qr_code_id": "sg-nex-ew-01",
        "name": "NEX Serangoon - e-waste collection point",
        "type": "e_waste",
        "accepted_waste_types": ["e_waste"],
        "latitude": 1.3506,
        "longitude": 103.8720,
        "address": "23 Serangoon Central, Singapore 556083",
        "opening_hours": "10:00-22:00",
    },
    {
        "qr_code_id": "sg-bugis-01",
        "name": "Bugis Junction - recycling bin",
        "type": "recycling",
        "accepted_waste_types": ["recycling"],
        "latitude": 1.2995,
        "longitude": 103.8556,
        "address": "200 Victoria Street, Singapore 188021",
        "opening_hours": "10:00-22:00",
    },
    {
        "qr_code_id": "sg-tampines-ew-01",
        "name": "Tampines Mall - e-waste point",
        "type": "e_waste",
        "accepted_waste_types": ["e_waste"],
        "latitude": 1.3525,
        "longitude": 103.9447,
        "address": "4 Tampines Central 5, Singapore 529510",
        "opening_hours": "10:00-22:00",
    },
    # --- One inactive bin, so the "out of service" path is demonstrable --------
    {
        "qr_code_id": "sg-nus-sci-01",
        "name": "NUS Faculty of Science - recycling bin (under maintenance)",
        "type": "recycling",
        "accepted_waste_types": ["recycling"],
        "latitude": 1.2971,
        "longitude": 103.7807,
        "address": "6 Science Drive 2, Singapore 117546",
        "opening_hours": "24 hours",
        "notes": "Temporarily removed for cleaning.",
        "active": False,
    },
]
